name = "blink_led_blackpill_stm32f401"
description = "Blink LED demo for BlackPill STM32F401"
version = "0.2.0-dev"
website = "https://github.com/godunko/a0b-examples"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["a0b", "embedded", "demo", "blackpill", "stm32f401"]

project-files = ["../gnat/blackpill_stm32f401.gpr"]

[configuration]
generate_ada = false
generate_c = false
generate_gpr = true

[[depends-on]]
a0b_armv7m_systick_clock_timer = "*"
a0b_stm32f401_gpio = "*"
a0b_timer = "*"
light_blackpill_stm32f401 = "*"
